#!/bin/bash
# Git-based HPC Deployment Script
# Use this after you've pushed your code to GitHub

echo "=========================================="
echo "HPC Deployment via Git Clone"
echo "=========================================="

# Configuration - UPDATE THESE
HPC_USER="your_username"
HPC_ADDRESS="hpc.institution.edu"
HPC_PROJECT_DIR="/home/${HPC_USER}/projects"
REPO_URL="https://github.com/Mohith1k-cshs/mri_foundation.git"
BRANCH="branch_1"

echo ""
echo "Step 1: SSH to HPC and clone repository"
echo "----------------------------------------"
echo "Run these commands on HPC:"
echo ""
echo "ssh ${HPC_USER}@${HPC_ADDRESS}"
echo "cd ${HPC_PROJECT_DIR}"
echo "git clone ${REPO_URL}"
echo "cd mri_foundation"
echo "git checkout ${BRANCH}"
echo ""

echo "Step 2: Transfer large data files (not in git)"
echo "-----------------------------------------------"
echo "Run these from your local machine:"
echo ""
echo "# Transfer MRI-CORE pretrained model (416 MB)"
echo "scp mri_foundation.pth ${HPC_USER}@${HPC_ADDRESS}:${HPC_PROJECT_DIR}/mri_foundation/"
echo ""
echo "# Transfer clinical data"
echo "scp patient_outcomes_mapping.csv ${HPC_USER}@${HPC_ADDRESS}:${HPC_PROJECT_DIR}/mri_foundation/"
echo ""
echo "# Transfer DICOM data (if not already on HPC shared storage)"
echo "scp -r C:/Users/kanthamnenm/Downloads/Segmentation_Input_Automated_Download ${HPC_USER}@${HPC_ADDRESS}:/data/mri/"
echo ""
echo "# Transfer NRRD masks"
echo "scp -r C:/Users/kanthamnenm/Downloads/Segmentation_Outputs_293 ${HPC_USER}@${HPC_ADDRESS}:/data/mri/"
echo ""
echo "# Transfer clinical Excel file"
echo "scp C:/Users/kanthamnenm/Downloads/Clinical_and_Other_Features.xlsx ${HPC_USER}@${HPC_ADDRESS}:/data/mri/"
echo ""

echo "Step 3: Setup environment on HPC"
echo "---------------------------------"
echo "After transferring files, run on HPC:"
echo ""
echo "cd ${HPC_PROJECT_DIR}/mri_foundation"
echo "module load python/3.11 cuda/12.4"
echo "python -m venv mri_env"
echo "source mri_env/bin/activate"
echo "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124"
echo "pip install -r requirements.txt"
echo ""

echo "Step 4: Update data paths and run"
echo "----------------------------------"
echo "Edit preprocess_mri_data.py to update paths, then:"
echo "chmod +x *.sh"
echo "sbatch preprocess_job.sh"
echo ""
echo "=========================================="
echo "Deployment script complete!"
echo "=========================================="
